<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY913P9A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY913P9A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY913P9A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY913P9A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY913P9A\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y913P9A',
    'container.build_id' => '2ff4d6fe',
    'container.build_time' => 1627736827,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY913P9A');
