<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], []],
    'api_tests_binarytodecimal_collection' => [[], ['_controller' => 'App\\Controller\\CompController::binarytodecimal', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\ApiResource\\Test', '_api_identifiers' => [], '_api_has_composite_identifier' => false, '_api_collection_operation_name' => 'binarytodecimal'], [], [['text', '/api/binarytodecimal']], [], []],
    'api_tests_decimaltobinary_collection' => [[], ['_controller' => 'App\\Controller\\CompController::decimaltobinary', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\ApiResource\\Test', '_api_identifiers' => [], '_api_has_composite_identifier' => false, '_api_collection_operation_name' => 'decimaltobinary'], [], [['text', '/api/decimaltobinary']], [], []],
    'api_tests_palindrom_collection' => [[], ['_controller' => 'App\\Controller\\CompController::palindrome', '_format' => null, '_stateless' => null, '_api_resource_class' => 'App\\ApiResource\\Test', '_api_identifiers' => [], '_api_has_composite_identifier' => false, '_api_collection_operation_name' => 'palindrom'], [], [['text', '/api/palindrom']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
